services:
  # MSSQL Database (Required for the App)
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todo-list-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  # OTel Collector (The heart of OpenTelemetry)
  # We will use this to show raw logs/traces in the terminal
  otel-collector:
    image: signoz/signoz-otel-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./signoz/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=demo-host,os.description=linux
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    restart: always

volumes:
  mssql-data:
